apiVersion: v1
data:
  .dockerconfigjson: eyJhdXRocyI6eyJyZWdpc3RyeS5kaWdpdGFsb2NlYW4uY29tIjp7InVzZXJuYW1lIjoiZG9wX3YxXzYyNTFmMzNlMzFhMDdhZDVlZDU3MTE4MGIyOTlkZmFkNGQ0MjQ2NzA1MjNhMTI0ZmJkMDljMjNjOGZkYzljZGQiLCJwYXNzd29yZCI6ImRvcF92MV82MjUxZjMzZTMxYTA3YWQ1ZWQ1NzExODBiMjk5ZGZhZDRkNDI0NjcwNTIzYTEyNGZiZDA5YzIzYzhmZGM5Y2RkIiwiYXV0aCI6IlpHOXdYM1l4WHpZeU5URm1Nek5sTXpGaE1EZGhaRFZsWkRVM01URTRNR0l5T1Rsa1ptRmtOR1EwTWpRMk56QTFNak5oTVRJMFptSmtNRGxqTWpOak9HWmtZemxqWkdRNlpHOXdYM1l4WHpZeU5URm1Nek5sTXpGaE1EZGhaRFZsWkRVM01URTRNR0l5T1Rsa1ptRmtOR1EwTWpRMk56QTFNak5oTVRJMFptSmtNRGxqTWpOak9HWmtZemxqWkdRPSJ9fX0=
kind: Secret
metadata:
  name: regsecret
  namespace: itwasum
type: kubernetes.io/dockerconfigjson
